webserver_static_sites:
  - name: site1.example.com
    root: /usr/share/nginx/site1.example.com
    repository: https://github.com/acritelli/example-static-site.git
ansible_user: vagrant
ansible_password: vagrant
ansible_connection: ssh
