---

- name: file module
  hosts: all
  gather_facts: no
  become: yes

  tasks:

    - name: Create a directory if it does not exist
      file:
        path: /etc/test
        state: directory

    - name: copy files from local to remote
      copy:
        src: files/test.txt
        dest: /etc/test/test.txt

    - name: test template
      template:
        src: templates/test.j2
        dest: /etc/test/test.cfg
